name: route_parser
description: A route parsing package for matching routes against each other and extracting params
version: 0.0.2
homepage: https://github.com/cedvdb/route_parser

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
